spring:
  datasource:
    url: jdbc:mysql://192.168.76.128:3306/db_test?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456